### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Cuirong1** [BeelGroup/Augmented-DonorsChoose.org-Dataset#1]
I am sorry to bother you. I would like to ask you about the data set of this experiment. Can you share it with me when it is convenient? thank you for your help.

**Comment by Cuirong1** [comment]
I don't know how the experimental dataset is set up. Can you tell me the column properties of each dataset? (Donations.csv;Donors.csv;Projects.csv;Schoole.csv).Thank you for your help!

**Comment by Edenhofer** [comment]
The dataset is freely available and directly located in the repository using git lfs. The path relative to the root of the project is [`data/meta-learner-items.csv`](https://github.com/BeelGroup/Augmented-DonorsChoose.org-Dataset/blob/master/data/meta-learner-items.csv). The columns in the augmented corpus are described briefly in the README in the section "[Corpus Features and Augmented Metadata](https://github.com/BeelGroup/Augmented-DonorsChoose.org-Dataset#corpus-features-and-augmented-metadata)". The original data which has been augmented is described in great detail at the [DonorsChoose.org kaggle challenge](https://www.kaggle.com/donorschoose/io).

I hope this information helps otherwise feel free to contact me again.

**Comment by Cuirong1** [comment]
Thank you for your reply!
